### ISSUE TITLE
node_modules/rxjs/Subject.d.ts(16,22): error TS2415: Class 'Subject<T>' incorrec tly extends base class 'Observable<T>'.

### ISSUE THREAD

**Issue by leotm** [xmaestro/sails-angular2#2]
After
`npm install`
`npm i typings -g`
`typings install`
`tsc`

![capture](https://user-images.githubusercontent.com/1881059/28500646-1bc1a4f4-6fcc-11e7-88bd-c299c616d3dd.PNG)

`sails lift` still works with an error-free console 🎉

**Comment by xmaestro** [comment]
Looks more like an incorrect typecasting issue. Reopen if you think it's different with more code.

**Comment by leotm** [comment]
Ah. The repo's on `"typescript": "2.3.4"`.
I updated to "typescript": "2.4.2".
I'm not getting the error anymore however.

Btw, it's an rxjs bug.
It's gone unnoticed until the later TypeScript 2.4.x compiler.

See: https://github.com/ReactiveX/rxjs/issues/2539

**Comment by leotm** [comment]
P.S. Thanks for your repo and the tut.
Only working Sails+Angular repo I've found.
Wasted lot of time and headache on scotch.io and others, riddled with bugs.
Keep up the updates man. This is gold for getting started.
